version: '2'
services:
  load-balancer-api:
    scale: 1
    lb_config:
      port_rules:
      - source_port: ${WEB_PORT}
        target_port: 8080
        service: config-register
  config-register:
    scale: 1
  vpn-server:
    scale: 1